Remove usage of unstable feature and unnecessary unsafe code
iamkroot/asus-numpad pull request #15
Opened 2023-01-15 19:14 UTC by Sporif

Makes it possible to build this crate with stable rust. And the performance seems fine without all the `*_unchecked`.

2023-01-16 18:06 UTC, iamkroot commented
While I can understand wanting to use the stable version of the compiler, there is no need to remove the `unsafe` code. The entire point of `unsafe` is that it lets us visibly mark when to disable some checks that we know are redundant. Unless `miri` is unhappy with something, I would ask you to revert these changes.

2023-01-16 18:06 UTC, iamkroot requested changes
While I can understand wanting to use the stable version of the compiler, there is no need to remove the unsafe code. The entire point of unsafe is that it lets us visibly mark when to disable some checks that we know are redundant. Unless miri is unhappy with something, I would ask you to revert these changes.

2023-01-16 18:10 UTC, Sporif commented
Ok, but I thought unsafe should be used only when absolutely necessary (i.e measurable performance gain, ffi etc).

2023-01-17 17:21 UTC, iamkroot approved these changes
Thanks for the update!

2023-01-17 17:21 UTC, merged