Touch enhancement
iamkroot/asus-numpad pull request #18
Opened 2023-01-25 22:43 UTC by encrustace

- [ ] Install Script added
- [ ]  Uninstall Script added
- [ ]  Touch and cursor movement are very accurate

2023-01-25 22:46 UTC, encrustace commented
@iamkroot  Please review and test, for me it is now touches are very accurate

2023-06-26 18:02 UTC, iamkroot commented on src/main.rs
>                          self.state.finger_state = FingerState::Touching;
Removing this code seems wrong. Now we can't hold a key to repeat it. 

> By default, when you hold down a key on your keyboard, the letter or symbol will be repeated until you release the key

(Gnome docs)

2023-06-26 18:05 UTC, iamkroot commented
Regarding the install script- I have an aversion to reading/writing shell scripts. Would much rather prefer a saner language such as python. (maybe you can get gpt to do it :P)

2024-01-22 18:24 UTC, encrustace commented
Hey @iamkroot  I have reverted the continue press code.
I have added autoselect layout in install script.
I choose bash to avoid python dependency.

A suggestion if you can integegrate layout auto selection in build itself, that would make it more easy to setup.

2024-08-11 04:00 UTC, iamkroot requested changes
As I see it, there's three changes in this PR:
1. Install/uninstall scripts
2. Jitter
3. UX325EA model name

Would be better to split them up into separate PRs so they are easier to review.

2024-08-11 04:00 UTC, iamkroot commented on install.sh
> +    keyboardModel=$(cat /sys/class/dmi/id/board_name)
This doesn't work if it is something other than one of the known models. It is also possible that a laptop has the same layout as one already supported - so it can reuse the same name. We should present a list of layouts to the user in case it doesn't belong to the ones we know of.

2024-08-11 04:00 UTC, iamkroot commented on src/main.rs
> +if self.state.pos.dist_sq(self.state.tap_start_pos) <= Self::TAP_JITTER_DIST {
Could we please put this change in a separate PR?

2024-08-11 04:00 UTC, iamkroot commented on src/main.rs
> -
Unnecessary. Please revert all whitespace changes

2024-08-11 04:00 UTC, iamkroot commented on src/main.rs
> +if self.state.pos.dist_sq(self.state.tap_start_pos) <= Self::TAP_JITTER_DIST {
Please ensure the file is properly formatted with `cargo fmt`.

2024-08-18 17:06 UTC, closed without merging